# to do list
# retrieve k3s_control_token from file (slurp with new hosts: ??)
# get 1 master up and running

- hosts: master:worker
  gather_facts: yes
  become: yes
  pre_tasks:
    - name: Set hostname
      hostname:
        name: "{{ hostname }}"

    - name: Add new hostname to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: '127.0.0.1 localhost {{ hostname }}'
        state: present

    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist

    - name: Check if a reboot is required
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the server
      reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

    - name: Install dependencies (apt)
      apt:
        name:
          - etcd
          - net-tools
          - curl
          - unattended-upgrades
          - apt-listchanges
          - apt-transport-https
        state: present
      when: "'master' in group_names"

    - name: Stop the etcd service
      systemd:
        state: stopped
        name: etcd
      when: "'master' in group_names"

    - name: Delete etcd data directory
      file:
        state: absent
        path: "/var/lib/etcd/"
      when: "'master' in group_names"

    - name: Create etcd data directory
      file:
        state: directory
        path: "/var/lib/etcd/"
        owner: etcd
        group: etcd
        mode: '700'
      when: "'master' in group_names"

    - name: Create etcd service override directory
      file:
        path: /etc/systemd/system/etcd.service.d/
        state: directory
      when: "'master' in group_names"

    - name: Create override file from template
      template:
        src: templates/etc/systemd/system/etcd.service.d/override.conf.j2
        dest: /etc/systemd/system/etcd.service.d/override.conf
        owner: root
        group: root
        mode: '0644'
      when: "'master' in group_names"

    - name: Daemon-reload, start and enable etcd service
      systemd:
        state: restarted
        daemon_reload: yes
        enabled: yes
        name: etcd
      when: "'master' in group_names"

# https://github.com/rancher/k3s/issues/1289
#    - name: Set each worker to be a worker node
#      set_fact:
#        k3s_node_labels:
#            - node-role.kubernetes.io/worker: worker
#      when: ansible_hostname in ['worker']

  roles:
    - xanmanning.k3s
