---
iface: ens33
ansible_port: 22

etcd_client_port: 2379
etcd_peer_port: 2380
etcd_protocol: http

k3s_release_version: stable
k3s_control_node: true
k3s_cluster_domain: ansible.iptables.sh
k3s_control_node_address: lb.ansible.iptables.sh
k3s_datastore_endpoint: http://lb.ansible.iptables.sh:2379
k3s_node_id: "{{ hostname | to_uuid }}"
k3s_kubelet_args: 
    - audit-log-path: /var/log/k8s_audit_log