---
# This should be set to a private network interface
iface: eth1

#Ansible SSH port, can also be set per host in hosts.ini
ansible_port: 22

# etcd configuration
etcd_client_port: 2379
etcd_peer_port: 2380
etcd_protocol: http
etcd_advertise_client_urls: http://161.35.155.187:2379
etcd_initial_cluster_token: etcd-cluster-1

# k3s configuration
k3s_release_version: stable
k3s_control_node: true
k3s_become_for_all: true
k3s_cluster_domain: ansible.iptables.sh
k3s_control_node_address: 161.35.155.187
k3s_datastore_endpoint: http://161.35.155.187:2379
k3s_node_id: "{{ ansible_hostname | to_uuid }}"

#For Calico
#k3s_flannel_backend: none
#k3s_cluster_cidr: 192.168.0.0/16

#Disable Traefik
#k3s_no_traefik: true