---
# This should be set to a private network interface
iface: eth1

#Ansible SSH port, can also be set per host in hosts.ini
ansible_port: 22

# etcd configuration
etcd_client_port: 2379
etcd_peer_port: 2380
etcd_protocol: http
etcd_advertise_client_urls: http://lb.ansible.iptables.sh:2379
etcd_initial_cluster_token: etcd-cluster-1

# k3s configuration
k3s_release_version: stable
k3s_control_node: true
k3s_become_for_all: true
k3s_cluster_domain: ansible.iptables.sh
k3s_control_node_address: lb.ansible.iptables.sh
k3s_datastore_endpoint: http://lb.ansible.iptables.sh:2379
k3s_node_id: "{{ ansible_hostname | to_uuid }}"
k3s_bind_address: "{{hostvars[host]['ansible_' + iface].ipv4.address}}"
k3s_node_ip_address: "{{hostvars[host]['ansible_' + iface].ipv4.address}}"

#For Calico
#k3s_flannel_backend: none
#k3s_cluster_cidr: 192.168.0.0/16